import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { PT_Sans } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { ActiveThemeProvider } from "@/components/active-theme";
import { cn } from "@/lib/utils"
import { ThemeProvider } from "next-themes";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const ptSans = PT_Sans({
  variable: "--font-pt-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  const cookieStore = await cookies()

  const activeThemeValue = cookieStore.get("active_theme")?.value
const isScaled = activeThemeValue?.endsWith("-scaled")

  
  return (
    <html lang="en" suppressHydrationWarning >
      <body
     className={cn(
      "bg-background overscroll-none font-sans antialiased",
      activeThemeValue ? `theme-${activeThemeValue}` : "",
      isScaled ? "theme-scaled" : "",
      `${nunito.variable} ${ptSans.variable}`,
    )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem  
          disableTransitionOnChange
          enableColorScheme
        >
        <ActiveThemeProvider initialTheme={activeThemeValue}>
          <div className="texture" />
            {children}
        </ActiveThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
